<?php

namespace App\Listener;

use App\Events\NewFlight;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use App\Insurance;

class SetInsurance
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  NewFlight  $event
     * @return void
     */
    public function handle(NewFlight $event)
    {
        $insurance = new Insurance();

        $insurance->price = rand(100000, 300000);
        $insurance->description = 'This insurance was generated by a trigger (event/listener)';
        $insurance->availability = (bool)random_int(0, 1);

        $event->flight->insurance()->save($insurance);
    }
}
